name: Monthly GitHub Metrics

on:
  schedule:
    # 09:00 PT on the 1st of each month (16:00 UTC)
    - cron: "0 16 1 * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, repositories
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: America/Los_Angeles

          # Languages panel (optional)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_recent_days: 365
          plugin_languages_categories: programming

          # Output settings: write and commit metrics.svg to the repo
          filename: metrics.svg
          output_action: commit
          committer_message: "Chore: Monthly metrics refresh"
